server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mycrew
    platform: mycrew
    username: mycrew
    password: mycrew
    driverClassName: org.postgresql.Driver

keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: mycrew
  resource: app-login
  public-client: true
  principal-attribute: preferred_username